name: Pytest & flake8 control Push
on: push

jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout on master
        uses: actions/checkout@v3  # This copies your code to the test machine

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"  # Install Python 3

      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8

      - name: Run tests
        run: |
          pytest

      - name: Run flake8
        uses: py-actions/flake8@v2  # Runs flake8 check
